### ISSUE TITLE
Consider changing default branch to "main"

### ISSUE THREAD

**Issue by asmecher** [ulsdevteam/COUNTER#1]
PKP has standardized on the use of `main` in place of `master` for the default (development) branch of its repos.

Our apps use this repo as a submodule, so to keep things standard, it would be great for the default branch of this repo to be renamed to `main` too. (Github has made this change for all new repos, FWIW.)

See these instructions: https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by ctgraham** [comment]
Renamed.
